<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
  <Reference Include="core">
    <HintPath>..\Common\core.dll</HintPath>
  </Reference>
  <Reference Include="scopes">
    <HintPath>..\Common\scopes.dll</HintPath>
  </Reference>
</ItemGroup>
</Project>